server:
  port: 8088  # Set the port for the payment service

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/eCommerce
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: payment_service  # Specify the schema for this microservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: payment_service  # Set the schema for Hibernate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: payment-service-group
    auto-offset-reset: earliest
    properties:
      spring:
        json:
          trusted:
            packages: '*'
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 10 seconds
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,prometheus