global:
  scrape_interval: 15s

scrape_configs:
  # Scrape configuration for Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape configuration for API Gateway
  - job_name: "api-gateway"
    static_configs:
      - targets: ["localhost:8082"]

  # Scrape configuration for Security Service
  - job_name: "security"
    static_configs:
      - targets: ["localhost:8083"]

  # Scrape configuration for User Service
  - job_name: "user-service"
    static_configs:
      - targets: ["localhost:8084"]

  # Scrape configuration for Order Service
  - job_name: "order-service"
    static_configs:
      - targets: ["localhost:8085"]

  # Scrape configuration for Product Service
  - job_name: "product-service"
    static_configs:
      - targets: ["localhost:8086"]

  # Scrape configuration for Inventory Service
  - job_name: "inventory-service"
    static_configs:
      - targets: ["localhost:8087"]

  # Scrape configuration for Payment Service
  - job_name: "payment-service"
    static_configs:
      - targets: ["localhost:8088"]

  # Scrape configuration for Shipping Service
  - job_name: "shipping-service"
    static_configs:
      - targets: ["localhost:8089"]

  # Scrape configuration for Keycloak
  - job_name: "keycloak"
    static_configs:
      - targets: ["localhost:8081"]

  # Scrape configuration for PostgreSQL (eCommerce) using exporter
  - job_name: "postgres-ecommerce"
    static_configs:
      - targets: ["localhost:9187"]

  # Scrape configuration for Elasticsearch
  - job_name: "elasticsearch"
    static_configs:
      - targets: ["localhost:9200"]

  # Scrape configuration for Logstash monitoring API
  - job_name: "logstash"
    static_configs:
      - targets: ["localhost:9600"]

  # Scrape configuration for Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"]
