server:
  port: 8083

spring:
  application:
    name: security-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: security-service-group
    auto-offset-reset: earliest
    properties:
      spring:
        json:
          trusted:
            packages: '*'
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

keycloak:
  auth-server-url: http://localhost:8081/realms/eCommerce/protocol/openid-connect
  client-id: api-gateway
  client-secret: IQU3cSySrxWH611nd6JQ8g1WK9eIZfhh
  realm: eCommerce

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
