server:
  port: 8083

spring:
  application:
    name: security-service
  mvc:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
  security:
    oauth2:
      client:
        registration:
          keycloak:
            realm: eCommerce
            auth-server-url: http://localhost:8081/realms/eCommerce/protocol/openid-connect
            client-id: api-gateway
            client-secret: IQU3cSySrxWH611nd6JQ8g1WK9eIZfhh
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/eCommerce
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/eCommerce
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: security-service-group
    auto-offset-reset: earliest
    properties:
      spring:
        json:
          trusted:
            packages: '*'
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf.CsrfFilter: DEBUG
    org.keycloak: DEBUG
