server:
  port: 8761  # Default port for Eureka Server

eureka:
  client:
    register-with-eureka: false  # The server doesn't need to register with itself
    fetch-registry: false  # It doesn't fetch any registry
  instance:
    hostname: localhost

spring:
  application:
    name: eureka-server
